// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Threading;
using Microsoft.Extensions.Logging;

namespace Bot.Resorces
{
    internal static class Common
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.Common", typeof(Common).GetTypeInfo().Assembly);

        /// <summary>
        ///     Followers: {followers} Status: {status}
        /// </summary>
        public static string Dialogs_HeroCard_Subtitle(object followers, object status)
            => string.Format(
                GetString("Dialogs_HeroCard_Subtitle", nameof(followers), nameof(status)),
                followers, status);

        /// <summary>
        ///     en-en
        /// </summary>
        public static string Locale
            => GetString("Locale");

        /// <summary>
        ///     No
        /// </summary>
        public static string No
            => GetString("No");

        /// <summary>
        ///     Yes
        /// </summary>
        public static string Yes
            => GetString("Yes");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

namespace Bot.Resorces.Internal
{
    internal static class Common
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.Common", typeof(Common).GetTypeInfo().Assembly);
    }
}
