// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Threading;
using Microsoft.Extensions.Logging;

namespace Bot.Resorces
{
    internal static class MarkEpisodeAsWhatched
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.MarkEpisodeAsWhatched", typeof(MarkEpisodeAsWhatched).GetTypeInfo().Assembly);

        /// <summary>
        ///     Do you mean the season {season} episode {episode} of {seriesName}?
        /// </summary>
        public static string MarkEpisodeAsWatchDTO_CheckConfirmation_Prompt(object season, object episode, object seriesName)
            => string.Format(
                GetString("MarkEpisodeAsWatchDTO_CheckConfirmation_Prompt", nameof(season), nameof(episode), nameof(seriesName)),
                season, episode, seriesName);

        /// <summary>
        ///     Answer yes or no.
        /// </summary>
        public static string MarkEpisodeAsWatchDTO_CheckConfirmation_RetryPrompt
            => GetString("MarkEpisodeAsWatchDTO_CheckConfirmation_RetryPrompt");

        /// <summary>
        ///     {season}x{episode} of {seriesName} watched.
        /// </summary>
        public static string MarkEpisodeAsWatchedDialog_MarkEpisode_Enter(object season, object episode, object seriesName)
            => string.Format(
                GetString("MarkEpisodeAsWatchedDialog_MarkEpisode_Enter", nameof(season), nameof(episode), nameof(seriesName)),
                season, episode, seriesName);

        /// <summary>
        ///     A lot of text. Go bookmark it on the TrackSeries website.
        /// </summary>
        public static string MarkEpisodeAsWatchedDialog_MarkEpisode_Skip
            => GetString("MarkEpisodeAsWatchedDialog_MarkEpisode_Skip");

        /// <summary>
        ///      o 
        /// </summary>
        public static string MarkEpisodeAsWatchedDialog_PromptCultureModel_InlineOr
            => GetString("MarkEpisodeAsWatchedDialog_PromptCultureModel_InlineOr");

        /// <summary>
        ///     
        /// </summary>
        public static string MarkEpisodeAsWatchedDialog_PromptCultureModel_InlineOrMore
            => GetString("MarkEpisodeAsWatchedDialog_PromptCultureModel_InlineOrMore");

        /// <summary>
        ///     ,
        /// </summary>
        public static string MarkEpisodeAsWatchedDialog_PromptCultureModel_Separator
            => GetString("MarkEpisodeAsWatchedDialog_PromptCultureModel_Separator");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

namespace Bot.Resorces.Internal
{
    internal static class MarkEpisodeAsWhatched
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.MarkEpisodeAsWhatched", typeof(MarkEpisodeAsWhatched).GetTypeInfo().Assembly);
    }
}
