// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Threading;
using Microsoft.Extensions.Logging;

namespace Bot.Resorces
{
    internal static class PendingEpisodes
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.PendingEpisodes", typeof(PendingEpisodes).GetTypeInfo().Assembly);

        /// <summary>
        ///     These are the pending chapters you have.
        /// </summary>
        public static string PendingEpisodesDialog_Carousel
            => GetString("PendingEpisodesDialog_Carousel");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

namespace Bot.Resorces.Internal
{
    internal static class PendingEpisodes
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.PendingEpisodes", typeof(PendingEpisodes).GetTypeInfo().Assembly);
    }
}
