// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Threading;
using Microsoft.Extensions.Logging;

namespace Bot.Resorces
{
    internal static class Trending
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.Trending", typeof(Trending).GetTypeInfo().Assembly);

        /// <summary>
        ///     Trending today, this week, this month, or forever?
        /// </summary>
        public static string TrendingDialog_AskForPeriod
            => GetString("TrendingDialog_AskForPeriod");

        /// <summary>
        ///     
        /// </summary>
        public static string TrendingDialog_Carusel
            => GetString("TrendingDialog_Carusel");

        /// <summary>
        ///     Forever
        /// </summary>
        public static string TrendingDialog_Forever
            => GetString("TrendingDialog_Forever");

        /// <summary>
        ///     Month
        /// </summary>
        public static string TrendingDialog_Month
            => GetString("TrendingDialog_Month");

        /// <summary>
        ///     Today
        /// </summary>
        public static string TrendingDialog_Today
            => GetString("TrendingDialog_Today");

        /// <summary>
        ///     Week
        /// </summary>
        public static string TrendingDialog_Week
            => GetString("TrendingDialog_Week");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

namespace Bot.Resorces.Internal
{
    internal static class Trending
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resorces.Trending", typeof(Trending).GetTypeInfo().Assembly);
    }
}
