// <auto-generated />

using System.Reflection;
using System.Resources;


namespace Bot.Resources
{
    internal static class Confirm
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resources.Confirm", typeof(Confirm).GetTypeInfo().Assembly);

        /// <summary>
        ///     No
        /// </summary>
        public static string No
            => GetString("No");

        /// <summary>
        ///      or
        /// </summary>
        public static string PromptCultureModel_InlineOr
            => GetString("PromptCultureModel_InlineOr");

        /// <summary>
        ///     
        /// </summary>
        public static string PromptCultureModel_InlineOrMore
            => GetString("PromptCultureModel_InlineOrMore");

        /// <summary>
        ///     ,
        /// </summary>
        public static string PromptCultureModel_Separator
            => GetString("PromptCultureModel_Separator");

        /// <summary>
        ///     Yes
        /// </summary>
        public static string Yes
            => GetString("Yes");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

namespace Bot.Resources.Internal
{
    internal static class Confirm
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Bot.Resources.Confirm", typeof(Confirm).GetTypeInfo().Assembly);
    }
}